"""Initial waitlist_emails table

Revision ID: 782d00037a61
Revises: 
Create Date: 2026-05-20 22:15:21.111335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782d00037a61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_emails', schema=None) as batch_op:
        batch_op.create_index('idx_waitlist_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_emails_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_emails_email'))
        batch_op.drop_index('idx_waitlist_created_at')

    op.drop_table('waitlist_emails')
    # ### end Alembic commands ###
